"""Constants for the package."""

from typing import Callable
from logging import WARNING, INFO, DEBUG, NOTSET, ERROR
from mega_snake.util import formatting

# Constants

APP_NAME: str = "mgsnake"
MODULE_NAME: str = "mega_snake"
INTERPRETER_PATH: str = ".venv/bin/python3.13"

# Packaged documentation fragments and the generated command reference
RESOURCES_DIR: str = "resources"
DOCS_DIR: str = "docs"
DOCS_FILE_SUFFIX: str = ".md"
DOCS_OUTPUT_FILE: str = "COMMANDS.md"

# Statuses meaning "the command succeeded, and the shell must now do something in its own session".
# A child process cannot mutate its parent's environment, so anything that changes the shell's
# variables has to be performed by the shell itself: the `mgsnake` function installed by
# config_setup.sh / config_setup.ps1 captures these statuses and calls the matching private helper.
# Changing either number breaks that contract: both scripts hard-code them, and so do the tests that
# pin the signals end to end.
#
# 29 — re-source the local config file (which loads its own .env in turn).
RELOAD_ENVIRONMENT_EXIT_CODE: int = 29
# 30 — load an env file. The shell re-reads the command's own arguments to know which one, so no
# value has to travel through stdout; see LOAD_ENV_COMMAND below.
LOAD_ENV_EXIT_CODE: int = 30

# The registered names of the two commands whose real work happens in the shell. The shell wrapper
# scans its arguments for these names to find where the command's own arguments begin, which is what
# lets `mgsnake --log-level DEBUG load-env foo.env` forward `foo.env` and nothing else. The literals
# are duplicated in config_setup.sh / config_setup.ps1 -- `test_shell_wrapper.py` fails if the two
# ever disagree, so keep them in sync rather than adding indirection the shell cannot resolve at
# profile time.
RELOAD_CONFIG_COMMAND: str = "reload-config"
LOAD_ENV_COMMAND: str = "load-env"

# The private shell helper that actually exports an env file. The local config file generated by
# `init-local-config` calls it directly instead of going through `mgsnake load-env`, because it is
# already being sourced *by* the shell: the exports land in the right session, and routing it back
# through the CLI would mean exiting 30 from inside a reload the wrapper is already performing.
# Defined in config_setup.sh / config_setup.ps1 under this exact name.
LOAD_ENV_HELPER: str = "__mgsnake_load_env"

REMOTE_BRANCHES_OPT: list[str] = ["M", "U", "A"]

# Jira integration. The store keys are shared by every jira_api module (and quoted back to the user
# in error messages as `mgsnake config set <key>`), so they live here rather than in one of them.
# Credentials are deliberately absent from this list: they are read from the environment only.
JIRA_DOMAIN_KEY: str = "jira.domain"
JIRA_EMAIL_KEY: str = "jira.email"
JIRA_PROJECT_KEY_KEY: str = "jira.project_key"
JIRA_BOARD_ID_KEY: str = "jira.board_id"
JIRA_STORY_POINTS_FIELD_KEY: str = "jira.field.story_points"
JIRA_SPRINT_FIELD_KEY: str = "jira.field.sprint"

JIRA_TOKEN_ENV: str = "JIRA_API_TOKEN"
# Only the auth header used to read JIRA_MCP_TOKEN while the other three scripts read
# JIRA_API_TOKEN. The two are unified on JIRA_API_TOKEN; this one stays as a deprecated fallback.
JIRA_DEPRECATED_TOKEN_ENV: str = "JIRA_MCP_TOKEN"
GITHUB_TOKEN_ENV: str = "GITHUB_TOKEN"

LOGGING_NAME_TO_LEVEL = {
    "ERROR": ERROR,
    "WARNING": WARNING,
    "INFO": INFO,
    "DEBUG": DEBUG,
    "NOTSET": NOTSET,
}
LOGGING_LEVEL_TO_NANE = {
    ERROR: "ERROR",
    WARNING: "WARNING",
    INFO: "INFO",
    DEBUG: "DEBUG",
    NOTSET: "NOTSET",
}
LOGGING_OPT: list[str] = list(LOGGING_NAME_TO_LEVEL.keys())
SHELL_OPT: list[str] = ["bash", "zsh", "powershell", "pwsh"]

MSG_OPT: dict[str, Callable] = {
    "S": formatting.ws_success,
    "I": formatting.ws_info,
    "W": formatting.ws_warning,
    "E": formatting.ws_error,
    "A": formatting.ws_advice,
    "T": formatting.ws_tip,
}

RELEASE_TYPE_OPT: dict[str, str] = {"p": "--prerelease", "r": "--latest=false", "l": "--latest"}

# Which component of a semantic version the new release tag increments. Bumping a component resets
# every component to its right, which is what keeps the sequence monotonic (1.2.3 -> 1.3.0, not 1.3.3).
VERSION_PART_OPT: dict[str, int] = {"patch": 2, "minor": 1, "major": 0}

GCLOUD_LOGGIN_OPT: dict[str, str] = {"U": "user", "A": "application", "B": "both"}

WORKSPACE_EXTENSIONS: list[str] = [
    "augustocdias.tasks-shell-input",
    "berublan.vscode-log-viewer",
    "bradzacher.vscode-copy-filename",
    "github.vscode-github-actions",
    "github.vscode-pull-request-github",
    "graphql.vscode-graphql-syntax",
    "graphql.vscode-graphql",
    "letmaik.git-tree-compare",
    "mhutchie.git-graph",
    "natqe.reload",
    "sandcastle.vscode-open",
    "solomonkinard.git-blame",
    "vscjava.vscode-gradle",
    "vscjava.vscode-java-pack",
]
