name: Copilot Setup Steps

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
      - .github/actions/setup-env/action.yml
      - .github/actions/setup-ai-context/action.yml

jobs:
  copilot-setup-steps: # This name is mandatory
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is mandatory to allow the action to read the repository contents
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up environment
        uses: ./.github/actions/setup-env
        with:
          requires-ai-context: "true"
          source-repo: ${{ secrets.AI_CONTEXT }}
          context-token: ${{ secrets.AI_CONTEXT_TOKEN }}
